# Generated by Django 5.0.1 on 2025-04-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('card', 'Credit Card'), ('paypal', 'PayPal')], default='cod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transport_method',
            field=models.CharField(choices=[('DHL Standard', 'DHL Standard'), ('Post - AT', 'Post - AT'), ('DHL Express Saver', 'DHL Express Saver')], default='DHL Standard', max_length=20),
        ),
    ]
