# Generated by Django 5.0.1 on 2025-07-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
