# Generated by Django 5.0.1 on 2026-04-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_orderitem_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubscription',
            name='checkout_order',
            field=models.ForeignKey(blank=True, help_text='Inicijalna porudžbina sa koje je pretplata kreirana (više pretplata po intervalu).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_subscriptions', to='account.order'),
        ),
    ]
