"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.21.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import environ
from corsheaders.defaults import default_headers
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Inicijalizujte environment
env = environ.Env(
    DEBUG=(bool, False)
)
# Učitajte .env fajl
environ.Env.read_env()




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(i1r#=#!6v%bs#_f-)qv8592g)ul2le4($wucvs%=7*2&0tu_3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

#TODO
ALLOWED_HOSTS = ['*']

GOOGLE_CLIENT_ID = '1073769483725-9r694i6s793d9ccmtfc2nh4tq4379s5a.apps.googleusercontent.com'


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'modeltranslation',
    'django.contrib.admin',
    'account',
    'email_campaign',

    'product',
    'backend',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'djmoney',
    'axes',
]

AUTH_USER_MODEL = 'account.CustomUser'
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:8081',
    'http://localhost:8000',
    'https://api.snusco.com',
    'https://www.snusco.com',
    'https://snusco.com',
    'https://*.maskkingsrbija.com',
    # Vercel: production, preview i branch deployevi (*.vercel.app)
    'https://*.vercel.app',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Pomereno bliže vrhu
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',  # Pomereno iznad LocaleMiddleware
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]


AXES_FAILURE_LIMIT = 15  # broj pokušaja pre nego što se blokira korisnik
AXES_COOLOFF_TIME = 2  # vreme blokade u satima

#SECURE_SSL_REDIRECT = True  # Preusmerava HTTP na HTTPS
SECURE_HSTS_SECONDS = 31536000  # Aktivira HSTS na 1 godinu
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Uključuje HSTS za sve subdomene
SECURE_CONTENT_TYPE_NOSNIFF = True  # Sprečava MIME-sniffing
SECURE_BROWSER_XSS_FILTER = True  # Aktivira browser XSS filter
X_FRAME_OPTIONS = 'DENY'  # Sprečava clickjacking napad



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'backend.asgi.application'
WSGI_APPLICATION = 'backend.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'axes': {
            'handlers': ['console'],  # Možete dodati fajl handler ako želite zapisivanje u fajl
            'level': 'INFO',  # INFO ili DEBUG za detaljnije praćenje
            'propagate': True,
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# else:
#     #zajedno sa dockerom radi
#     DATABASES = {
#         'default': {
#             'ENGINE': env('DB_ENGINE'),
#             'NAME': env('DB_NAME'),
#             'USER': env('DB_USER'),
#             'PASSWORD': env('DB_PASSWORD'),
#             'HOST': env('DB_HOST'),
#             'PORT': env('DB_PORT'),
#         }
#     }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://localhost:8081',
#     'http://localhost:8000',
#     'https://api.snusplus.com',
#     'https://www.snusplus.com',
#     'https://snusplus.com',
#     'https://api.nikotinskevrecice.com',
#     'https://www.nikotinskevrecice.com',
#     'https://nikotinskevrecice.com'
# ]

CORS_ALLOW_ALL_ORIGINS = True

# default_headers + app-specific; ne definiši ručno ceo spisak da ne izostane nešto (preflight / Axios "Network Error")
CORS_ALLOW_HEADERS = list(default_headers) + [
    'currency',
    'accept-language',
    'x-domain',
]



TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Setovanje podrazumevanog jezika
LANGUAGE_CODE = 'en-us'  # Podrazumevani jezik, ne radi
LANGUAGES = (
    ('en-us', 'American English'),
    ('de', 'German'),
    ('it', 'Italian'),
    ('fr', 'French'),
    ('hu', 'Hungarian'),
    ('tr', 'Turkish'),
    ('sr-latn', 'Serbian (Latin)'),  # Dodavanje srpskog jezika (latinično pismo)
)
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en-us'  # Podrazumevani jezik za modeltranslation, ako ga koristite




# Ostale relevantne postavke
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]
#AUTENTIFIKACIJA
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=61),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# AWS podešavanja
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_SIGNATURE_NAME = env('AWS_S3_SIGNATURE_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME')
AWS_S3_FILE_OVERWRITE = env.bool('AWS_S3_FILE_OVERWRITE', default=False)
AWS_DEFAULT_ACL = env('AWS_DEFAULT_ACL', default=None)
AWS_S3_VERIFY = env.bool('AWS_S3_VERIFY', default=True)

# Default file storage
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# EMAIL preko Mailjet SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "in-v3.mailjet.com"                # was: smtp.sendgrid.net
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)

EMAIL_HOST_USER = env("MAILJET_API_KEY")        # was: "apikey"
EMAIL_HOST_PASSWORD = env("MAILJET_SECRET_KEY") # was: <SendGrid key>

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")


# Celery podešavanja
CELERY_BROKER_URL = env('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = env.list('CELERY_ACCEPT_CONTENT', default=['json'])
CELERY_TASK_SERIALIZER = env('CELERY_TASK_SERIALIZER', default='json')
CELERY_RESULT_SERIALIZER = env('CELERY_RESULT_SERIALIZER', default='json')
CELERY_TIMEZONE = env('CELERY_TIMEZONE', default='UTC')

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    "process-due-product-subscriptions": {
        "task": "account.tasks.process_due_subscriptions",
        "schedule": crontab(minute=15, hour="*/4"),
    },
}

STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY')

MOLLIE_API_KEY = env('MOLLIE_API_KEY')

# Google Sheets API Key
GOOGLE_SHEET_API_KEY = env('GOOGLE_SHEET_API_KEY')

###CUSTOM USAGE
DEFAULT_DOMAIN = 'snusco.com'
# Jedan web shop — globalni limit nikotina po kesici (mg)
MAX_NICOTINE_MG_PER_POUCH = 999
#USE_POINTS = ['snusco.com']
#ALLOW_FREE_DELIVERY = ['snusco.com']
USE_POINTS = []
ALLOW_FREE_DELIVERY = []
