# Generated by Django 5.0.1 on 2025-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_flavor_alter_product_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('In Stock', 'IN_STOCK'), ('On Request', 'ON_REQUEST'), ('Out of Stock', 'OUT_OF_STOCK')], default='In Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='state',
            field=models.CharField(choices=[('In Stock', 'IN_STOCK'), ('On Request', 'ON_REQUEST'), ('Out of Stock', 'OUT_OF_STOCK')], default='In Stock', max_length=50),
        ),
    ]
