# Generated by Django 5.0.1 on 2025-07-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_state_alter_specialoffer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('country_code', models.CharField(max_length=2)),
                ('max_nicotine_mg_per_pouch', models.PositiveIntegerField(default=999, help_text='Maksimalna jačina nikotina po kesici u mg')),
            ],
        ),
        migrations.DeleteModel(
            name='DomainMapping',
        ),
    ]
