# Generated by Django 5.0.1 on 2025-07-19 08:13

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_frontend_delete_domainmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=product.models.ProductState.choices, default=product.models.ProductState['IN_STOCK'], max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('frontend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availabilities', to='product.frontend')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'frontend')},
            },
        ),
    ]
