# Generated by Django 5.0.1 on 2025-07-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='state',
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='state',
            field=models.CharField(choices=[('in_stock', 'IN_STOCK'), ('on_request', 'ON_REQUEST'), ('out_of_stock', 'OUT_OF_STOCK')], default='in_stock', max_length=50),
        ),
    ]
