# Generated by Django 5.0.1 on 2025-07-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_state_alter_specialoffer_state'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productseo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productseo',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='specialofferseo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='specialofferseo',
            name='special_offer',
        ),
        migrations.DeleteModel(
            name='CategorySEO',
        ),
        migrations.DeleteModel(
            name='ProductSEO',
        ),
        migrations.DeleteModel(
            name='SpecialOfferSEO',
        ),
    ]
