# Generated by Django 5.0.1 on 2026-07-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_specialoffer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
