# Generated by Django 5.0.1 on 2025-04-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('email_template', models.CharField(choices=[('promo', 'Promotional Email'), ('new_arrival', 'New Arrival Email'), ('discount', 'Discount Email')], default='promo', max_length=50)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='promotions', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_orders', models.IntegerField(default=5)),
                ('days_since_last_order', models.IntegerField(default=14)),
                ('promotion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='email_campaign.productpromotion')),
            ],
        ),
    ]
